### ISSUE TITLE
base64.encodestring() was removed from Python 3.9, encodebytes() should be used instead

### ISSUE THREAD

**Issue by shogunbr** [collective/collective.jsonmigrator#45]
from https://github.com/python/cpython/issues/83532:
base64.encodestring() and base64.decodestring() are aliases deprecated since Python 3.1: encodebytes() and decodebytes() should be used instead.

https://github.com/collective/collective.jsonmigrator/blob/64bcbdfb582c6aec12edb9ef881e5880134ef977/src/collective/jsonmigrator/blueprints/source_remote.py#L2

https://github.com/collective/collective.jsonmigrator/blob/64bcbdfb582c6aec12edb9ef881e5880134ef977/src/collective/jsonmigrator/blueprints/source_remote.py#L74

**Comment by wesleybl** [comment]
Fix in #50
