### ISSUE TITLE
Cleanup: collective.blueprint.jsonmigrator -> collective.jsonmigrator

### ISSUE THREAD

**Issue by jean** [collective/collective.jsonmigrator#6]
It looks like `collective.jsonmigrator` still contains vestiges of `collective.blueprint.jsonmigrator` code. E.g. there are same-same but different `class DataFields` providing `ISectionBlueprint` in both `blueprint.py` and `datafields.py`. Only the latter is registered in `configure.zcml`.
Other recipes (e.g. `PartialCommit`) are only in `blueprint.py`, and not registered in `configure.zcml`. I guess they may need work to be usable.

**Comment by thet** [comment]
should be fixed with:
https://github.com/collective/collective.jsonmigrator/pull/4
and
https://github.com/collective/collective.jsonmigrator/pull/8
